### ISSUE TITLE
Request object may be used instead of $_GET

### ISSUE THREAD

**Issue by omitobi** [OgunsakinDamilola/laravel-interswitch#2]
First, Kudos for your efforts in making this package. While I have not used it myself, but reading through the code here: https://github.com/OgunsakinDamilola/laravel-interswitch/blob/91ba8662b736408c2df66fadf2820baf937efcab/src/Http/Controllers/InterswitchController.php#L55 I see `Request` can be used instead of `$_GET`.

**Comment by ogunsakin01** [comment]
Yes, thank's for noting that out. I must have over looked it while making the updates. I have updated that now. Thanks a lot
