### ISSUE TITLE
The package need some tests

### ISSUE THREAD

**Issue by omitobi** [OgunsakinDamilola/laravel-interswitch#3]
Although Interswitch API does not need to be tested, but since this package also provides interaction to db and controller feeding data to and consuming from interswitch API, tests are needed.

This will make Maintenance and refactoring easier.

**Comment by ogunsakin01** [comment]
Currently working on that Omitobi, will sure push the updates when I am done. Thanks once again for giving your experience

**Comment by ogunsakin01** [comment]
Added
